services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.enrollment.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms6g -Xmx6g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ES_PORT}:9200"
      - "9300:9300"
    networks: [elastic]
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:${ELASTIC_PASSWORD} http://127.0.0.1:9200/_cluster/health | egrep -q '\"status\":\"(green|yellow)\"'"]
      interval: 30s
      timeout: 10s
      retries: 10

  # Set the kibana_system password on first run (required by Elastic’s sample)
  setup-kibana-user:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    depends_on: [elasticsearch]
    entrypoint: >
      bash -euo pipefail -c '
        until curl -s -u elastic:${ELASTIC_PASSWORD} http://elasticsearch:9200/_cluster/health |
          egrep -q "\"status\":\"(green|yellow)\""; do
          echo "Waiting for ES..."; sleep 3;
        done
        curl -fsS -X POST -u elastic:${ELASTIC_PASSWORD} http://elasticsearch:9200/_security/user/kibana_system/_password \
          -H "Content-Type: application/json" \
          -d "{\"password\":\"${KIBANA_PASSWORD}\"}"
        echo "kibana_system password set."
       '
    networks: [elastic]

  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - SERVER_HOST=0.0.0.0
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${KIBANA_ENCRYPTION_KEY}
      - XPACK_SECURITY_ENCRYPTIONKEY=${KIBANA_ENCRYPTION_KEY}
      - XPACK_REPORTING_ENCRYPTIONKEY=${KIBANA_ENCRYPTION_KEY}
    ports:
      - "5601:5601"
    networks: [elastic]
    depends_on:
      elasticsearch:
        condition: service_healthy
      setup-kibana-user:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:${ELASTIC_PASSWORD} http://127.0.0.1:5601/api/status | egrep -q '\"state\":\"(green|available)\"'"]
      interval: 30s
      timeout: 10s
      retries: 10

networks:
  elastic:
    driver: bridge
